### ISSUE TITLE
Framed message format description is inconsistent with specification

### ISSUE THREAD

**Issue by mattsb42-aws** [awsdocs/aws-encryption-sdk-docs#8]
The issue on the spec has been resolved. I think this should be sufficient to clear up the gap we had with the docs.

https://github.com/awslabs/aws-encryption-sdk-specification/issues/51

**Comment by juneb** [comment]
Fixed by commit: 2eaa5124b4ca8b66d8ea3fad1d99f00024069405. Thanks for the issue.
